fix GeographicLib 2.0
ros-noetic-arch/ros-noetic-libmavconn pull request #2
Opened 2022-06-18 19:46 UTC by AchmadFathoni

This PR should make the ros-noetic-mavros can be build with GeographicLib 2.0. I want to use patch from upstream PR but there is no noetic branch.

2022-06-19 00:33 UTC, acxz requested changes

2022-06-19 00:33 UTC, acxz commented on PKGBUILD
> +  sed -i '11s/Geographic)/GeographicLib)/' ${_dir}/cmake/Modules/FindGeographicLib.cmake
The branch to make a PR against is `master`. ROS1 releases/tags follow the master branch for that project.

2022-06-19 00:33 UTC, acxz commented
Since this is a patch, please make a corresponding issue for the error or warning message you are receiving.

2022-07-01 12:14 UTC, acxz commented
@AchmadFathoni bump
can you make an issue, b4 I merge this in?

2022-07-01 12:15 UTC, acxz approved these changes

2022-07-02 01:53 UTC, AchmadFathoni commented
> @AchmadFathoni bump can you make an issue, b4 I merge this in?

Here or upstream?

2022-07-02 03:06 UTC, acxz commented
Here, it'll be the issue that we close once the patch is not needed.

2022-07-08 21:08 UTC, merged